name: SelenoidTest

on:
  workflow_dispatch:
    inputs:
      browsers:
        description: 'Browser for tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox

jobs:
   MavenBuildWithSelenoid:
    runs-on: ubuntu-latest

    steps:
      - name: Pull the project into the runner
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1
        
      - name: Build and run tests step
        run: mvn clean test -Dsuite=pdp-rozetka -Dbrowser=${{inputs.browsers}}
        
      - name: Create artifacts directory
        if: success() || failure()
        run: mkdir artifacts && cp -r reports artifacts

      - name: Upload artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: artifacts
