name: gitHubActionsArtifacts

on:
  push:
    branches: [ master ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
          
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
         source: https://github.com/oshcherbina17/gitHubActionsWithSelenoid/actions/
         destination: screenshot.png
         full-page: true
           
