name: publishTestResult

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Run tests and collect coverage
        run: mvn clean test -Dsuite=selenoid
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
    #  - name: Build and run tests
     #   run: mvn clean test -Dsuite=selenoid

    #  - name: Upload Test Coverage
   #     uses: codecov/codecov-action@v2
  #      with:
   #       token: ${{ secrets.SECRET_TOKEN }}
   #       files: -Dsuite=selenoid
    #      version: "v0.1.15"

     # - name: Generate Test Report
       # uses: codecov/codecov-action@v2
        #with:
       #   token: ${{ secrets.SECRET_TOKEN }}
      #    files: -Dsuite=selenoid
     #     version: "v0.1.15"
    #      fail_ci_if_error: true

